files:
  ignore:
    - node_modules/**/*
    - bower_components/**/*
    - jspm_packages/**/*
rules:
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  function-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  max-file-line-count:
    - 1
    -
      length: 500
  max-line-length:
    - 1
    -
      length: 100
  leading-zero:
    - 1
    -
      include: true
  nesting-depth:
    - 1
    -
      max-depth: 5
  no-color-literals: 0
  no-debug: 0
  no-important: 0
  no-qualifying-elements: 0
  no-transition-all: 0
  no-url-domains: 0
  no-vendor-prefixes: 0
  no-warn: 0
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  property-sort-order:
    - 1
    -
      order: concentric
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
